language: node_js
node_js:
- node
before_script:
- npm install grunt-cli -g
env:
  global:
    secure: 2zeRVifoXGIblF5KSkFjP2aVNKx+8cuYCQdOlFS+g36ZOdFWWM6XfUri+nXgs7fncMsUgQOZ/6U9ZAQUlgxjs+0T+IZTNCc39QcYbwyh3WtyvHg7zBliysxk1UqTAtTfXkWwqQZheq7IxksvuxngDPQD/pn/bd1PGDWiDo3Dn9Ujb9o8A7n0EF0Twfo//yQtlRAemT4NBXi3caVwsuMZjCfJoxruMVtdXQXTclVc+Rxg3szJDKzXrDoCYszFa08uXBxPbKML0xSOJFVug9DrJcqQTJlrzIuf7UUq94EJ1PAVEOI+1HhQ6f29YE2qroy95H/2a4GCLh5fHdS2RdTfIR8VWumP/B/gRLhLYYj1cdVlXq1KYkR3gsrswyvXHBu9kLxy4GfR17iRHjOPMRdA5uIU2oInHf44ot2aXuVaEUxBSdgTq4IIOSsezAK9gvzFvP8dqjrFdlwCK3tj4FalFysdljh9vJ6fWQuCFRscdTS80yYdWImOjxgUnEg5XMncxaBcrVL/hictn5ylN1FZDJPUROJ1pdzDIEEy2soxkwcYyfiVoiNsKuGw+W6C/oKPI580eEed0Dlyl9HBk96Mo/Os2wRwMDhtkOH0sJ3DBBPvHMRtAX8r3iI1gA/VNi05CtkNXqp/nS6EtIxE49Im7MoQWtQBcYubnkAyABKCq5c=
