language: node_js
node_js:
- node
before_script:
- npm install grunt-cli -g
env:
  global:
    secure: Au3cW6slO9uvQaUfF0Dcza6VSzPnV3CjKdxwT2NiV48cva13jIlpB4+Vqx5Cadix0H6MtQ1c6zERGU0vrUtQgAa91y0QZIrPLUy+WpxsGVhooBEXJ6N3jheSbeDD8C0w5ThyOaGov1RanPdIFgOu8h2zBnPej07OI4FSxKqyxDjJNqbEuCLJRTQt19/onUAEZvTHxUKC6z5NT8J9IT4uIXpbzLNe8/ckW3brjJ/82XaPugLrgRiVb+3BF3CThcQtAUNgFvRIgfdZPlcIj8eYqVTexULkHnUYld09y8Kl0CNySqdw9z8uWsoS+cuwcM9r2Fo52elb03Y1syK5m2AI0U3XVNKgEEtrHI9PUXX9G70Vmg1QoxoqcF0g+4gb+wEFrdiLksjqyxIQ3XrczBCzmGgfnyIb7yqjlrqfDukdKzyYffodyR8MmGhTpmmdNJWQh9dILFbt6UBgoc5P2BIvbPA5cpA9g24wjMwxRYo1W+y80kblZztqp6WVpy6zqlKudQ5M24p1PNuFm8h1b7Txv8E1vEYmatzAj8r8F/ezZ6seBzrDoZklgVYMuKZLi3wvSYi5Ly3BqLBJcxWfIafPXH70qYit5v4dAFuygb5hks82fw57h9isE/qteoE8j4Gmb7Z2udbooAb77uzBuCkAlts6Q7z9HlQ2brsqN/K/BHg=
